spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: MyProject
  datasource:
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/next_tech
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jinbaominenterprise@gmail.com
    password: xmlmbtealtsavxkz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



server:
  port: 8081
  servlet:
    context-path: /next-tech

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

open:
  api:
    title: Next Tech Core API
    version: v1.0.0
    description: API document for Next Tech Core API
    serverUrl: http://localhost:8081
    serverName: server test

jwt:
  secret_key: "jfkdla5475940325jfidsafjdjf9403ufdafdsafeafe22"
  expiration_time: 86400000
  auth_header: "Authorization"



